spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  thymeleaf:
    cache: false
logging:
  level:
    net.ujacha: debug
    org.hibernate.SQL: debug

app:
  title: UJACHA BOARD